[package]
name = "futuruna-web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "=0.7.10", features = ["fullstack", "router"] }
futuruna = { path = ".." }
gloo-timers = { version = "0.3", features = ["futures"] }
lucide-dioxus = { version = "=3.31.0", features = ["text"] }
pulldown-cmark = "0.12"

[features]
default = ["web"]
web = ["dioxus/web"]
server = ["dioxus/server"]

[build-dependencies]
futuruna = { path = ".." }
