[application]
name = "futuruna-web"
default_platform = "web"
asset_dir = "public"

[web.app]
title = "Futuruna - A Programming Language for Law"

[web.watcher]
watch_path = ["src", "assets", "public"]
