//! Project manifests (`runa.toml`), lock files (`runa.lock`) and the local
//! dependency store.
//!
//! Everything in this module reads local files only. Git dependencies are
//! downloaded exclusively by `runa add` and `runa fetch`; import resolution,
//! checking and the language server use the checkout recorded in `runa.lock`
//! and report an error when it is not present.

use sha2::{Digest, Sha256};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

pub const MANIFEST_FILE: &str = "runa.toml";
pub const LOCK_FILE: &str = "runa.lock";

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum DependencySource {
    /// A directory, relative to the manifest unless absolute.
    Path(String),
    /// A Git repository. `url` is an https://, ssh:// or git@host:path URL, or
    /// a local repository path (relative to the manifest unless absolute).
    Git { url: String, rev: Option<String> },
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Dependency {
    pub name: String,
    pub source: DependencySource,
}

#[derive(Clone, Debug)]
pub struct Manifest {
    pub path: PathBuf,
    pub name: String,
    pub version: String,
    pub dependencies: Vec<Dependency>,
}

impl Manifest {
    pub fn directory(&self) -> &Path {
        self.path.parent().unwrap_or_else(|| Path::new("."))
    }

    pub fn dependency(&self, name: &str) -> Option<&Dependency> {
        self.dependencies
            .iter()
            .find(|dependency| dependency.name == name)
    }

    pub fn lock_path(&self) -> PathBuf {
        self.directory().join(LOCK_FILE)
    }
}

/// One `runa.lock` entry: the manifest source it was resolved from, plus the
/// exact commit for Git dependencies.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LockedDependency {
    pub name: String,
    pub source: DependencySource,
    pub commit: Option<String>,
}

#[derive(Clone, Debug, Default)]
pub struct Lockfile {
    pub dependencies: Vec<LockedDependency>,
}

impl Lockfile {
    pub fn entry(&self, name: &str) -> Option<&LockedDependency> {
        self.dependencies.iter().find(|entry| entry.name == name)
    }

    /// The commit locked for `dependency`, when the lock entry was resolved
    /// from the same manifest source.
    pub fn locked_commit(&self, dependency: &Dependency) -> Option<&str> {
        let entry = self.entry(&dependency.name)?;
        (entry.source == dependency.source)
            .then_some(entry.commit.as_deref())
            .flatten()
    }

    pub fn render(&self) -> String {
        let mut out = String::from(
            "# Generated by `runa add` and `runa fetch`. Commit this file with runa.toml.\n\n[dependencies]\n",
        );
        for entry in &self.dependencies {
            let _ = write!(out, "{} = {{ ", entry.name);
            match &entry.source {
                DependencySource::Path(path) => {
                    let _ = write!(out, "path = {}", toml_string(path));
                }
                DependencySource::Git { url, rev } => {
                    let _ = write!(out, "git = {}", toml_string(url));
                    if let Some(rev) = rev {
                        let _ = write!(out, ", rev = {}", toml_string(rev));
                    }
                }
            }
            if let Some(commit) = &entry.commit {
                let _ = write!(out, ", commit = {}", toml_string(commit));
            }
            out.push_str(" }\n");
        }
        out
    }
}

/// Render a dependency for `runa.toml`.
pub fn dependency_line(dependency: &Dependency) -> String {
    match &dependency.source {
        DependencySource::Path(path) => {
            format!("{} = {{ path = {} }}", dependency.name, toml_string(path))
        }
        DependencySource::Git { url, rev: None } => {
            format!("{} = {{ git = {} }}", dependency.name, toml_string(url))
        }
        DependencySource::Git {
            url,
            rev: Some(rev),
        } => format!(
            "{} = {{ git = {}, rev = {} }}",
            dependency.name,
            toml_string(url),
            toml_string(rev)
        ),
    }
}

fn toml_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

/// Find the manifest governing `start_dir`: the nearest `runa.toml` in it or
/// an ancestor. The search never leaves the enclosing version-control
/// checkout, so a manifest above the repository root does not apply.
pub fn find_manifest(start_dir: &Path) -> Option<PathBuf> {
    let start = if start_dir.as_os_str().is_empty() {
        Path::new(".")
    } else {
        start_dir
    };
    let mut dir = std::fs::canonicalize(start).unwrap_or_else(|_| start.to_path_buf());
    loop {
        let candidate = dir.join(MANIFEST_FILE);
        if candidate.is_file() {
            return Some(candidate);
        }
        if [".git", ".hg", ".jj"]
            .iter()
            .any(|marker| dir.join(marker).exists())
        {
            return None;
        }
        if !dir.pop() {
            return None;
        }
    }
}

pub fn parse_manifest(path: &Path) -> Result<Manifest, String> {
    let content = std::fs::read_to_string(path)
        .map_err(|error| format!("cannot read {}: {}", path.display(), error))?;
    parse_manifest_source(path, &content)
}

pub fn parse_manifest_source(path: &Path, content: &str) -> Result<Manifest, String> {
    let mut name = None;
    let mut version = String::from("0.1.0");
    let mut dependencies: Vec<Dependency> = Vec::new();
    let mut section = Section::None;
    let located =
        |line: usize, message: String| format!("{}:{}: {}", path.display(), line, message);

    for (index, raw_line) in content.lines().enumerate() {
        let line_number = index + 1;
        let line = strip_comment(raw_line).trim();
        if line.is_empty() {
            continue;
        }
        if line.starts_with('[') {
            section = match line {
                "[package]" => Section::Package,
                "[dependencies]" => Section::Dependencies,
                other => return Err(located(
                    line_number,
                    format!(
                        "unsupported section `{other}`; runa.toml has [package] and [dependencies]"
                    ),
                )),
            };
            continue;
        }
        let (key, value) = split_key_value(line)
            .ok_or_else(|| located(line_number, "expected `key = value`".to_string()))?;
        match section {
            Section::None => {
                return Err(located(
                    line_number,
                    format!("`{key}` must appear inside [package] or [dependencies]"),
                ))
            }
            Section::Package => {
                let value = parse_string(value).map_err(|error| located(line_number, error))?;
                match key {
                    "name" => name = Some(value),
                    "version" => version = value,
                    "entry" => {}
                    other => {
                        return Err(located(
                            line_number,
                            format!(
                                "unknown [package] key `{other}`; expected name, version or entry"
                            ),
                        ))
                    }
                }
            }
            Section::Dependencies => {
                validate_dependency_name(key).map_err(|error| located(line_number, error))?;
                if dependencies.iter().any(|dependency| dependency.name == key) {
                    return Err(located(
                        line_number,
                        format!("dependency `{key}` is declared more than once"),
                    ));
                }
                let table = parse_inline_table(value).map_err(|error| {
                    located(
                        line_number,
                        format!("dependency `{key}`: {error}; write `{key} = {{ path = \"...\" }}` or `{key} = {{ git = \"...\" }}`"),
                    )
                })?;
                let (source, commit) = dependency_source(&table, false).map_err(|error| {
                    located(line_number, format!("dependency `{key}`: {error}"))
                })?;
                debug_assert!(commit.is_none());
                dependencies.push(Dependency {
                    name: key.to_string(),
                    source,
                });
            }
        }
    }

    let name = name
        .filter(|name| !name.is_empty())
        .ok_or_else(|| format!("{}: [package] needs a `name`", path.display()))?;
    Ok(Manifest {
        path: path.to_path_buf(),
        name,
        version,
        dependencies,
    })
}

/// Read `runa.lock` next to the manifest. A missing lock file is empty.
pub fn read_lockfile(manifest: &Manifest) -> Result<Lockfile, String> {
    let path = manifest.lock_path();
    let content = match std::fs::read_to_string(&path) {
        Ok(content) => content,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return Ok(Lockfile::default())
        }
        Err(error) => return Err(format!("cannot read {}: {}", path.display(), error)),
    };
    let located =
        |line: usize, message: String| format!("{}:{}: {}", path.display(), line, message);
    let mut lockfile = Lockfile::default();
    let mut in_dependencies = false;
    for (index, raw_line) in content.lines().enumerate() {
        let line_number = index + 1;
        let line = strip_comment(raw_line).trim();
        if line.is_empty() {
            continue;
        }
        if line.starts_with('[') {
            if line != "[dependencies]" {
                return Err(located(
                    line_number,
                    format!("unsupported section `{line}`"),
                ));
            }
            in_dependencies = true;
            continue;
        }
        if !in_dependencies {
            return Err(located(line_number, "expected [dependencies]".to_string()));
        }
        let (key, value) = split_key_value(line)
            .ok_or_else(|| located(line_number, "expected `name = { ... }`".to_string()))?;
        validate_dependency_name(key).map_err(|error| located(line_number, error))?;
        let table = parse_inline_table(value).map_err(|error| located(line_number, error))?;
        let (source, commit) = dependency_source(&table, true)
            .map_err(|error| located(line_number, format!("dependency `{key}`: {error}")))?;
        lockfile.dependencies.push(LockedDependency {
            name: key.to_string(),
            source,
            commit,
        });
    }
    Ok(lockfile)
}

/// Per-user cache root shared by all Futuruna caches.
pub fn user_cache_root() -> Option<PathBuf> {
    if let Some(path) = std::env::var_os("XDG_CACHE_HOME").map(PathBuf::from) {
        if path.is_absolute() {
            return Some(path.join("futuruna"));
        }
    }
    let home = PathBuf::from(std::env::var_os("HOME")?);
    Some(if cfg!(target_os = "macos") {
        home.join("Library/Caches/futuruna")
    } else {
        home.join(".cache/futuruna")
    })
}

/// Directory holding every fetched commit of one Git source.
pub fn git_source_store(url_identity: &str) -> Option<PathBuf> {
    let digest = Sha256::digest(url_identity.as_bytes());
    let key: String = digest
        .iter()
        .take(12)
        .map(|byte| format!("{byte:02x}"))
        .collect();
    Some(user_cache_root()?.join("deps").join("git").join(key))
}

/// The absolute location git should fetch from. Local repository paths are
/// relative to the manifest directory.
pub fn git_fetch_location(url: &str, manifest_dir: &Path) -> String {
    if is_local_git_path(url) && !Path::new(url).is_absolute() {
        manifest_dir.join(url).to_string_lossy().into_owned()
    } else {
        url.to_string()
    }
}

/// The checkout of `commit` for a Git source in the local store.
pub fn git_checkout_dir(url: &str, manifest_dir: &Path, commit: &str) -> Option<PathBuf> {
    Some(git_source_store(&git_fetch_location(url, manifest_dir))?.join(commit))
}

fn is_local_git_path(url: &str) -> bool {
    url.starts_with('/') || url.starts_with("./") || url.starts_with("../")
}

pub fn validate_git_url(url: &str) -> Result<(), String> {
    let unsupported = || {
        format!("unsupported git source `{url}`; use an https://, ssh:// or git@host:path URL, or a local path starting with /, ./ or ../")
    };
    if url.is_empty()
        || url.starts_with('-')
        || url.chars().any(|ch| ch.is_control() || ch.is_whitespace())
    {
        return Err(unsupported());
    }
    let remote = url
        .strip_prefix("https://")
        .or_else(|| url.strip_prefix("ssh://"));
    if let Some(rest) = remote {
        let host = rest.split('/').next().unwrap_or("");
        let host = host.rsplit('@').next().unwrap_or("");
        if host.is_empty() || host.starts_with('-') || !rest.contains('/') {
            return Err(unsupported());
        }
        return Ok(());
    }
    if let Some(rest) = url.strip_prefix("git@") {
        let (host, path) = rest.split_once(':').ok_or_else(unsupported)?;
        let host_ok = !host.is_empty()
            && !host.starts_with('-')
            && host
                .chars()
                .all(|ch| ch.is_ascii_alphanumeric() || ch == '.' || ch == '-');
        if !host_ok || path.is_empty() || path.starts_with('-') {
            return Err(unsupported());
        }
        return Ok(());
    }
    if is_local_git_path(url) {
        return Ok(());
    }
    Err(unsupported())
}

/// A branch, tag or commit name. Anything git could read as an option or a
/// revision expression is rejected.
pub fn validate_git_rev(rev: &str) -> Result<(), String> {
    let valid = !rev.is_empty()
        && rev.len() <= 255
        && rev
            .chars()
            .next()
            .is_some_and(|ch| ch.is_ascii_alphanumeric() || ch == '_')
        && rev
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '.' | '_' | '/' | '-' | '+'))
        && !rev.contains("..")
        && !rev.contains("//")
        && !rev.ends_with('/')
        && !rev.ends_with('.')
        && !rev.ends_with(".lock");
    if valid {
        Ok(())
    } else {
        Err(format!(
            "invalid git rev `{rev}`; use a branch, tag or commit name such as `main`, `v1.2.0` or a commit hash"
        ))
    }
}

pub fn is_commit_hash(value: &str) -> bool {
    matches!(value.len(), 40 | 64)
        && value
            .chars()
            .all(|ch| ch.is_ascii_digit() || ('a'..='f').contains(&ch))
}

pub fn validate_dependency_name(name: &str) -> Result<(), String> {
    if !name.is_empty()
        && name
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || ch == '_' || ch == '-')
    {
        Ok(())
    } else {
        Err(format!(
            "invalid dependency name `{name}`; use letters, digits, `_` and `-`"
        ))
    }
}

/// The directory of a declared dependency, using only local files.
pub fn dependency_root(manifest: &Manifest, dependency: &Dependency) -> Result<PathBuf, String> {
    match &dependency.source {
        DependencySource::Path(path) => {
            let root = manifest.directory().join(path);
            if root.is_dir() {
                Ok(root)
            } else {
                Err(format!(
                    "dependency `{}` path `{}` does not exist",
                    dependency.name,
                    root.display()
                ))
            }
        }
        DependencySource::Git { url, .. } => {
            let fetch_hint = format!("run `runa fetch` in {}", manifest.directory().display());
            let lockfile = read_lockfile(manifest)?;
            let commit = lockfile.locked_commit(dependency).ok_or_else(|| {
                format!(
                    "git dependency `{}` is not locked in {}; {}",
                    dependency.name, LOCK_FILE, fetch_hint
                )
            })?;
            let root = git_checkout_dir(url, manifest.directory(), commit).ok_or_else(|| {
                "cannot locate the dependency cache (HOME is not set)".to_string()
            })?;
            if root.is_dir() {
                Ok(root)
            } else {
                Err(format!(
                    "git dependency `{}` at commit {} is not fetched; {}",
                    dependency.name,
                    &commit[..12.min(commit.len())],
                    fetch_hint
                ))
            }
        }
    }
}

/// Resolve `dependency/module` (or bare `dependency`, meaning its `lib`
/// module) against the manifest governing `dir`. Returns `None` when the
/// first path segment is not a declared dependency.
pub fn resolve_dependency_import(import_path: &str, dir: &Path) -> Option<Result<PathBuf, String>> {
    let (name, module) = match import_path.split_once('/') {
        Some((name, module)) => (name, module),
        None => (import_path, "lib"),
    };
    let manifest_path = find_manifest(dir)?;
    let manifest = match parse_manifest(&manifest_path) {
        Ok(manifest) => manifest,
        Err(error) => return Some(Err(error)),
    };
    let dependency = manifest.dependency(name)?;
    Some(dependency_root(&manifest, dependency).and_then(|root| {
        let direct = root.join(format!("{module}.runa"));
        if direct.is_file() {
            return Ok(direct);
        }
        let nested = root.join("src").join(format!("{module}.runa"));
        if nested.is_file() {
            return Ok(nested);
        }
        Err(format!(
            "dependency `{}` has no module `{}` (searched {} and {})",
            name,
            module,
            direct.display(),
            nested.display()
        ))
    }))
}

#[derive(Clone, Copy)]
enum Section {
    None,
    Package,
    Dependencies,
}

fn strip_comment(line: &str) -> &str {
    let mut quote = None;
    let mut escaped = false;
    for (index, ch) in line.char_indices() {
        match quote {
            Some('"') if escaped => escaped = false,
            Some('"') if ch == '\\' => escaped = true,
            Some(open) if ch == open => quote = None,
            Some(_) => {}
            None if ch == '"' || ch == '\'' => quote = Some(ch),
            None if ch == '#' => return &line[..index],
            None => {}
        }
    }
    line
}

fn split_key_value(line: &str) -> Option<(&str, &str)> {
    let (key, value) = line.split_once('=')?;
    let key = key.trim();
    let key = key
        .strip_prefix('"')
        .and_then(|key| key.strip_suffix('"'))
        .unwrap_or(key);
    Some((key, value.trim()))
}

/// Parse one TOML basic ("...") or literal ('...') string occupying `value`.
fn parse_string(value: &str) -> Result<String, String> {
    let (parsed, rest) = parse_string_prefix(value)?;
    if !rest.trim().is_empty() {
        return Err(format!("unexpected `{}` after string", rest.trim()));
    }
    Ok(parsed)
}

fn parse_string_prefix(value: &str) -> Result<(String, &str), String> {
    let mut chars = value.char_indices();
    let quote = match chars.next() {
        Some((_, ch @ ('"' | '\''))) => ch,
        _ => return Err("expected a quoted string".to_string()),
    };
    let mut out = String::new();
    while let Some((index, ch)) = chars.next() {
        if ch == quote {
            return Ok((out, &value[index + 1..]));
        }
        if quote == '"' && ch == '\\' {
            match chars.next() {
                Some((_, '"')) => out.push('"'),
                Some((_, '\\')) => out.push('\\'),
                Some((_, 'n')) => out.push('\n'),
                Some((_, 't')) => out.push('\t'),
                _ => return Err("unsupported escape in string".to_string()),
            }
            continue;
        }
        out.push(ch);
    }
    Err("unterminated string".to_string())
}

fn parse_inline_table(value: &str) -> Result<Vec<(String, String)>, String> {
    let inner = value
        .strip_prefix('{')
        .and_then(|value| value.strip_suffix('}'))
        .ok_or_else(|| "expected an inline table `{ ... }`".to_string())?;
    let mut entries: Vec<(String, String)> = Vec::new();
    let mut rest = inner.trim();
    while !rest.is_empty() {
        let (key, after_key) = rest
            .split_once('=')
            .ok_or_else(|| "expected `key = \"value\"`".to_string())?;
        let key = key.trim().to_string();
        let (value, after_value) = parse_string_prefix(after_key.trim_start())?;
        if entries.iter().any(|(existing, _)| *existing == key) {
            return Err(format!("key `{key}` appears more than once"));
        }
        entries.push((key, value));
        let after_value = after_value.trim_start();
        rest = match after_value.strip_prefix(',') {
            Some(next) => next.trim_start(),
            None if after_value.is_empty() => "",
            None => return Err(format!("unexpected `{after_value}`")),
        };
    }
    Ok(entries)
}

fn dependency_source(
    table: &[(String, String)],
    lock: bool,
) -> Result<(DependencySource, Option<String>), String> {
    let get = |key: &str| {
        table
            .iter()
            .find(|(candidate, _)| candidate == key)
            .map(|(_, value)| value.clone())
    };
    for (key, _) in table {
        let allowed = matches!(key.as_str(), "path" | "git" | "rev") || (lock && key == "commit");
        if !allowed {
            return Err(format!(
                "unsupported key `{key}`; dependencies have `path`, or `git` with an optional `rev`"
            ));
        }
    }
    let commit = get("commit");
    match (get("path"), get("git")) {
        (Some(path), None) => {
            if get("rev").is_some() || commit.is_some() {
                return Err("`rev` applies only to git dependencies".to_string());
            }
            if path.is_empty() {
                return Err("`path` is empty".to_string());
            }
            Ok((DependencySource::Path(path), None))
        }
        (None, Some(url)) => {
            validate_git_url(&url)?;
            let rev = get("rev");
            if let Some(rev) = &rev {
                validate_git_rev(rev)?;
            }
            if lock {
                match &commit {
                    Some(commit) if is_commit_hash(commit) => {}
                    Some(commit) => {
                        return Err(format!("`commit` `{commit}` is not a full commit hash"))
                    }
                    None => return Err("git entries need a `commit`".to_string()),
                }
            }
            Ok((DependencySource::Git { url, rev }, commit))
        }
        (Some(_), Some(_)) => Err("use either `path` or `git`, not both".to_string()),
        (None, None) => Err("missing `path` or `git`".to_string()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn git_sources_that_git_could_read_as_options_are_rejected() {
        for url in [
            "--upload-pack=touch /tmp/x",
            "-oProxyCommand=x",
            "ext::sh -c touch% /tmp/x",
            "http://example.com/repo.git",
            "file:///tmp/repo",
            "git@-oProxyCommand=x:repo",
            "https://-host/repo",
            "host:repo",
        ] {
            assert!(validate_git_url(url).is_err(), "{url}");
        }
        for url in [
            "https://github.com/Futuruna/futuruna",
            "ssh://git@example.com/team/repo.git",
            "git@github.com:Futuruna/futuruna.git",
            "/srv/git/repo.git",
            "../shared.git",
        ] {
            assert!(validate_git_url(url).is_ok(), "{url}");
        }
    }

    #[test]
    fn revisions_must_be_ref_or_hash_shaped() {
        for rev in [
            "--output=/tmp/x",
            "-b",
            "HEAD@{1}",
            "main..evil",
            "a b",
            "v1.lock",
            "",
        ] {
            assert!(validate_git_rev(rev).is_err(), "{rev:?}");
        }
        for rev in [
            "main",
            "v1.2.0",
            "release/0.2",
            "0123456789abcdef0123456789abcdef01234567",
        ] {
            assert!(validate_git_rev(rev).is_ok(), "{rev}");
        }
    }

    #[test]
    fn manifest_dependencies_reject_unknown_keys_and_bare_strings() {
        let path = Path::new("runa.toml");
        let parse = |deps: &str| {
            parse_manifest_source(
                path,
                &format!("[package]\nname = \"p\"\n\n[dependencies]\n{deps}\n"),
            )
        };
        assert!(parse("a = \"../a\"").is_err());
        assert!(parse("a = { path = \"../a\", branch = \"x\" }").is_err());
        assert!(parse("a = { git = \"--upload-pack=x\" }").is_err());
        assert!(parse("a = { path = \"../a\", rev = \"main\" }").is_err());
        let manifest = parse(
            "a = { path = \"../git-tools\" } # comment\nb = { git = \"https://example.com/b\", rev = \"v1\" }",
        )
        .unwrap();
        assert_eq!(
            manifest.dependencies[0].source,
            DependencySource::Path("../git-tools".into())
        );
        assert_eq!(
            manifest.dependencies[1].source,
            DependencySource::Git {
                url: "https://example.com/b".into(),
                rev: Some("v1".into())
            }
        );
    }

    #[test]
    fn lock_entries_apply_only_to_the_same_manifest_source() {
        let commit = "0123456789abcdef0123456789abcdef01234567".to_string();
        let lockfile = Lockfile {
            dependencies: vec![LockedDependency {
                name: "b".into(),
                source: DependencySource::Git {
                    url: "https://example.com/b".into(),
                    rev: None,
                },
                commit: Some(commit.clone()),
            }],
        };
        let rendered = lockfile.render();
        let dependency = |rev: Option<&str>| Dependency {
            name: "b".into(),
            source: DependencySource::Git {
                url: "https://example.com/b".into(),
                rev: rev.map(str::to_string),
            },
        };
        assert_eq!(
            lockfile.locked_commit(&dependency(None)),
            Some(commit.as_str())
        );
        assert_eq!(lockfile.locked_commit(&dependency(Some("v2"))), None);
        assert!(rendered.contains(&format!(
            "b = {{ git = \"https://example.com/b\", commit = \"{commit}\" }}"
        )));
    }
}
